server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: native

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 2
      connection-timeout: 20000

  jpa:
    show-sql: false

logging:
  level:
    tech.nocountry.talent.appbitservice: INFO

app:
  jwt:
    secret: ${JWT_SECRET}